# Generated by Django 3.1.7 on 2022-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='Trackexpence.png', upload_to='profile_image'),
        ),
    ]
